# Generated by Django 4.2.7 on 2023-12-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textdatasource',),
        ),
        migrations.CreateModel(
            name='OriginalText',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.rawtext',),
        ),
        migrations.CreateModel(
            name='RestoredText',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.processedtext',),
        ),
        migrations.CreateModel(
            name='StrippedText',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.preprocessedtext',),
        ),
    ]
