# Generated by Django 4.2.7 on 2024-01-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationJob',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Job',
                'verbose_name_plural': 'Restoration Jobs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingjob',),
        ),
        migrations.CreateModel(
            name='RestorationJobRun',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Job Run',
                'verbose_name_plural': 'Restoration Job Runs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingjobrun',),
        ),
        migrations.CreateModel(
            name='RestorationJobRunOutput',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Job Run Output',
                'verbose_name_plural': 'Restoration Job Run Outputs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingoutput',),
        ),
        migrations.CreateModel(
            name='RestorationOutput',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Output',
                'verbose_name_plural': 'Restoration Outputs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingoutput',),
        ),
        migrations.CreateModel(
            name='RestorationPromptTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Prompt Template',
                'verbose_name_plural': 'Restoration Prompt Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.prompttemplate',),
        ),
    ]
