# Generated by Django 4.2.7 on 2023-12-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('json_file', models.FileField(upload_to='datasources/')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glife.datasource')),
            ],
        ),
    ]
