# Generated by Django 4.2.7 on 2023-12-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_textdatasource_scope'),
        ('glife', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('textdatasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.textdatasource')),
            ],
            bases=('core.textdatasource',),
        ),
    ]
