# Generated by Django 4.2.7 on 2023-12-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_textprocessingjobrun_created_at_alter_llm_version_and_more'),
        ('glife', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OriginalText',
        ),
        migrations.DeleteModel(
            name='RestoredText',
        ),
        migrations.DeleteModel(
            name='StrippedText',
        ),
        migrations.CreateModel(
            name='RestorationJob',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Job',
                'verbose_name_plural': 'Restoration Jobs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingjob',),
        ),
        migrations.AlterModelOptions(
            name='restorationprompttemplate',
            options={'verbose_name': 'Restoration Prompt Template', 'verbose_name_plural': 'Restoration Prompt Templates'},
        ),
    ]
