# Generated by Django 4.2.7 on 2023-12-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_prompttemplate_name_alter_llm_version'),
        ('glife', '0002_delete_datasource_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.prompttemplate',),
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textdatasource',),
        ),
    ]
