# Generated by Django 4.2.7 on 2024-01-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_textprocessingjobrun_finished_at'),
        ('glife', '0002_delete_originaltext_delete_restoredtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorationJobRun',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Job Run',
                'verbose_name_plural': 'Restoration Job Runs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingjobrun',),
        ),
        migrations.CreateModel(
            name='RestorationJobRunOutput',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Job Run Output',
                'verbose_name_plural': 'Restoration Job Run Outputs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingoutput',),
        ),
        migrations.CreateModel(
            name='RestorationOutput',
            fields=[
            ],
            options={
                'verbose_name': 'Restoration Output',
                'verbose_name_plural': 'Restoration Outputs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.textprocessingoutput',),
        ),
    ]
