# Generated by Django 4.2.7 on 2023-12-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glife', '0003_rename_alteredtext_preprocessedtext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprocessedtext',
            old_name='alteration_function',
            new_name='preprocessing_function',
        ),
        migrations.RenameField(
            model_name='preprocessedtext',
            old_name='alteration_function_kwargs',
            new_name='preprocessing_function_kwargs',
        ),
    ]
