services:
  summa-db:
    image: postgres:latest
    ports:
      - 0:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: summa
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  summa-app:
    image: summa:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      summa-db:
        condition: service_healthy
  metabase-db:
    image: postgres:latest
    ports:
      - 0:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metabase
  metabase:
    image: metabase/metabase:latest
    ports:
      - 8005:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
