services:
  galandriel-db:
    image: postgres:latest
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: galandriel
    volumes:
      - galandriel-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  galandriel-app:
    image: summa/galandriel:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - galandriel-app-media:/summa/galandriel/media
    depends_on:
      galandriel-db:
        condition: service_healthy
  metabase-db:
    image: postgres:latest
    ports:
      - 5010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metabase
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase:latest
    ports:
      - 8010:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
volumes:
  galandriel-db-data:
  galandriel-app-media:
  metabase-db-data:
