# Generated by Django 4.2.7 on 2023-12-21 07:35

import core.models
import core.models_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(editable=False, max_length=200)),
                ('version', models.CharField(choices=[('OPENAI_GPT_3_5_TURBO', 'OPENAI_GPT_3_5_TURBO'), ('OPENAI_GPT_4', 'OPENAI_GPT_4'), ('META_LLAMA_2_70B_CHAT_HF', 'META_LLAMA_2_70B_CHAT_HF'), ('META_LLAMA_2_7B_CHAT_HF', 'META_LLAMA_2_7B_CHAT_HF'), ('DEEPINFRA_AIROBOROS_70B', 'DEEPINFRA_AIROBOROS_70B'), ('MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1', 'MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1')], max_length=200)),
            ],
            options={
                'verbose_name': 'LLM',
                'verbose_name_plural': 'LLMs',
            },
        ),
        migrations.CreateModel(
            name='PreprocessedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_md5', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5 hash')),
                ('file', models.FileField(help_text='Upload a prompt template file.', upload_to=core.models.prompt_template_upload_path, verbose_name='Prompt Template File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Upload a JSON file containing the text data for this data source.', upload_to=core.models.data_source_upload_path, validators=[core.models_validators.datasource_validate_json], verbose_name='JSON File')),
            ],
        ),
        migrations.CreateModel(
            name='TextPreprocessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textdatasource')),
                ('llms', models.ManyToManyField(to='core.llm')),
                ('preprocessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textpreprocessor')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessor')),
                ('prompt_templates', models.ManyToManyField(to='core.prompttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RawText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_md5', models.CharField(editable=False, max_length=32, unique=True, verbose_name='MD5 hash')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textdatasource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('generation_time', models.FloatField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preprocessedtext')),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.llm')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessor')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prompttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='preprocessedtext',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawtext'),
        ),
        migrations.AddField(
            model_name='preprocessedtext',
            name='preprocessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textpreprocessor'),
        ),
    ]
