# Generated by Django 4.2.7 on 2023-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdatasource',
            name='scope',
            field=models.CharField(default='core', editable=False, max_length=200),
        ),
    ]
