# Generated by Django 4.2.7 on 2023-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jsondatasource',
            options={'verbose_name': 'JSON Data Source', 'verbose_name_plural': 'JSON Data Sources'},
        ),
        migrations.AlterField(
            model_name='textpreprocessor',
            name='name',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('STRIP_DIACRITICS', 'STRIP_DIACRITICS')], max_length=200),
        ),
        migrations.AlterField(
            model_name='textprocessor',
            name='name',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('RESTORE_DIACRITICS', 'RESTORE_DIACRITICS')], max_length=200),
        ),
    ]
