# Generated by Django 4.2.7 on 2024-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='version',
            field=models.CharField(choices=[('SUMMA_ECHO', 'SUMMA_ECHO'), ('OPENAI_GPT_3_5_TURBO', 'OPENAI_GPT_3_5_TURBO'), ('OPENAI_GPT_4', 'OPENAI_GPT_4'), ('OPENAI_GPT_4_TURBO', 'OPENAI_GPT_4_TURBO'), ('OPENAI_GPT_4o', 'OPENAI_GPT_4o'), ('META_LLAMA_2_7B_CHAT_HF', 'META_LLAMA_2_7B_CHAT_HF'), ('META_LLAMA_2_70B_CHAT_HF', 'META_LLAMA_2_70B_CHAT_HF'), ('META_LLAMA_3_8B_INSTRUCT', 'META_LLAMA_3_8B_INSTRUCT'), ('META_LLAMA_3_70B_INSTRUCT', 'META_LLAMA_3_70B_INSTRUCT'), ('DEEPINFRA_AIROBOROS_70B', 'DEEPINFRA_AIROBOROS_70B'), ('MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1', 'MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='textprocessingjobrun',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('RECOVERING', 'Recovering')], default='CREATED', max_length=200),
        ),
    ]
