# Generated by Django 4.2.7 on 2023-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jsondatasource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textpreprocessor',
            options={'verbose_name': 'Text Preprocessor', 'verbose_name_plural': 'Text Preprocessors'},
        ),
        migrations.AlterModelOptions(
            name='textprocessor',
            options={'verbose_name': 'Text Processor', 'verbose_name_plural': 'Text Processors'},
        ),
        migrations.AddField(
            model_name='textpreprocessor',
            name='description',
            field=models.TextField(default='N/A', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textprocessor',
            name='description',
            field=models.TextField(default='N/A', editable=False),
            preserve_default=False,
        ),
    ]
