# Generated by Django 4.2.7 on 2023-12-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_textdatasource_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdatasource',
            name='scope',
            field=models.CharField(max_length=200),
        ),
    ]
