# Generated by Django 4.2.7 on 2023-12-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_textpreprocessor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProcessingJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='STARTED', max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessingjob')),
            ],
        ),
        migrations.CreateModel(
            name='TextProcessingJobRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessed_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preprocessedtext')),
                ('processed_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processedtext')),
                ('raw_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawtext')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessingjobrun')),
            ],
        ),
    ]
