# Generated by Django 4.2.7 on 2023-12-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_textdatasource_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdatasource',
            name='scope',
        ),
    ]
