# Generated by Django 4.2.7 on 2023-12-21 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_textprocessingjobrun_textprocessingjobrunresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='textprocessingjobrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llm',
            name='version',
            field=models.CharField(choices=[('OPENAI_GPT_3_5_TURBO', 'OPENAI_GPT_3_5_TURBO'), ('OPENAI_GPT_4', 'OPENAI_GPT_4'), ('META_LLAMA_2_70B_CHAT_HF', 'META_LLAMA_2_70B_CHAT_HF'), ('META_LLAMA_2_7B_CHAT_HF', 'META_LLAMA_2_7B_CHAT_HF'), ('DEEPINFRA_AIROBOROS_70B', 'DEEPINFRA_AIROBOROS_70B'), ('MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1', 'MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='textprocessingjobrun',
            name='finished_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='textprocessingjobrun',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='textprocessingjobrun',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='CREATED', max_length=200),
        ),
    ]
