# Generated by Django 4.2.7 on 2023-12-22 07:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_textprocessingjobrun_created_at_alter_llm_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('F1_SCORE_WORDS', 'F1 Score (Words)'), ('F1_SCORE_CHARS', 'F1 Score (Chars)'), ('CHARACTER_ACCURACY', 'Character Accuracy'), ('WORD_ACCURACY', 'Word Accuracy')], max_length=200, unique=True)),
                ('description', models.TextField(editable=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='llm',
            options={'ordering': ['model', 'version'], 'verbose_name': 'LLM', 'verbose_name_plural': 'LLMs'},
        ),
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='file',
            field=models.FileField(help_text='Upload a prompt template file.', unique=True, upload_to=core.models.prompt_template_upload_path, verbose_name='Prompt Template File'),
        ),
        migrations.AlterField(
            model_name='textpreprocessor',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic Text Preprocessor'), ('STRIP_DIACRITICS', 'Strip Diacritics Preprocessor')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='textprocessor',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic Text Processor')], max_length=200, unique=True),
        ),
    ]
