# Generated by Django 4.2.7 on 2023-12-20 20:06

import core.models
import core.models_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_textdatasource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdatasource',
            name='file',
            field=models.FileField(help_text='Upload a JSON file containing the text data for this data source.', upload_to=core.models.data_source_upload_path, validators=[core.models_validators.datasource_validate_json], verbose_name='JSON File'),
        ),
        migrations.AlterField(
            model_name='textdatasource',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
