# Generated by Django 4.2.7 on 2023-12-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_evals_textprocessingjob_evaluators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProcessingEvaluatorOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evaluator')),
            ],
        ),
        migrations.CreateModel(
            name='TextProcessingJobRunOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preprocessed_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preprocessedtext')),
                ('raw_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawtext')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessingjobrun')),
            ],
        ),
        migrations.CreateModel(
            name='TextProcessingOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('output', models.TextField()),
                ('generation_time', models.FloatField()),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.llm')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prompttemplate')),
                ('run_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessingjobrunoutput')),
            ],
        ),
        migrations.DeleteModel(
            name='TextProcessingJobRunResult',
        ),
        migrations.AddField(
            model_name='textprocessingevaluatoroutput',
            name='processing_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.textprocessingoutput'),
        ),
    ]
