# Generated by Django 4.2.7 on 2023-12-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_textdatasource_file_alter_textdatasource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdatasource',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
