# Generated by Django 4.2.7 on 2023-12-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_textprocessingevaluatoroutput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textprocessingjobrun',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
