# Generated by Django 4.2.7 on 2023-12-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_llm_unique_together_alter_llm_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llm',
            options={'verbose_name': 'LLM', 'verbose_name_plural': 'LLMs'},
        ),
    ]
