# Generated by Django 4.2.7 on 2023-12-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_llm_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='name',
            field=models.CharField(default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
