# Generated by Django 4.2.7 on 2024-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_textprocessingjobrun_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='text_md5',
            field=models.CharField(editable=False, max_length=32, verbose_name='MD5 hash'),
        ),
        migrations.AlterField(
            model_name='rawtext',
            name='text_md5',
            field=models.CharField(editable=False, max_length=32, verbose_name='MD5 hash'),
        ),
    ]
