# Generated by Django 4.2.7 on 2024-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_prompttemplate_text_md5_alter_rawtext_text_md5'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawtext',
            index=models.Index(fields=['text_md5'], name='core_rawtex_text_md_06aea6_idx'),
        ),
    ]
