# Generated by Django 4.2.7 on 2023-12-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_llm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llm',
            old_name='name',
            new_name='model',
        ),
    ]
