# Generated by Django 4.2.7 on 2023-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_name_llm_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompttemplate',
            name='name',
        ),
        migrations.AlterField(
            model_name='llm',
            name='version',
            field=models.CharField(choices=[('OPENAI_GPT_3_5_TURBO', 'OPENAI_GPT_3_5_TURBO'), ('OPENAI_GPT_4', 'OPENAI_GPT_4'), ('META_LLAMA_2_70B_CHAT_HF', 'META_LLAMA_2_70B_CHAT_HF'), ('META_LLAMA_2_7B_CHAT_HF', 'META_LLAMA_2_7B_CHAT_HF'), ('DEEPINFRA_AIROBOROS_70B', 'DEEPINFRA_AIROBOROS_70B'), ('MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1', 'MISTRALAI_MIXTRAL_8X7B_INSTRUCT_V0_1')], max_length=200),
        ),
    ]
